### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by steelbrain** [sindresorhus/shell-path#10] opened 2016-02-13 00:31 UTC
Got this stack trace from [a report](https://github.com/AtomLinter/linter-php/issues/131) filed by @rickgregory over on `linter-php`: 

``` text
TypeError: Cannot read property 'length' of null
    at SyncWriteStream.write (fs.js:1981:38)
    at Object.execFileSync (child_process.js:471:20)
    at pathFromShellSync (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/node_modules/shell-path/index.js:52:28)
    at Function.module.exports.sync (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/node_modules/shell-path/index.js:34:11)
    at findOutPath (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:27:62)
    at getPath (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:17:16)
    at _exec (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:61:59)
    at Object.exec (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:152:10)
```

**Comment by steelbrain** [comment] 2016-02-13 05:11
This is the line producing the error

```
return clean(childProcess.execFileSync(shell, ['-i', '-c', 'echo "$PATH"'], opts)) || '';
```

**Comment by silverwind** [comment] 2016-02-13 13:37
~~I think this is a Node.js bug, likely introduced in https://github.com/nodejs/node/commit/05d30d53965066583df352631226c6808558d960, but I'm not sure which of those two `.length` accesses is the problematic one.~~

~~@rickgregory Do we know which version of Node.js is used in that particular Atom release, so we can pinpoint the exact line of the error?~~

~~cc: @ronkorving~~

**Comment by silverwind** [comment] 2016-02-13 13:43
Or rather, scrap that suspicion. It's happening in `SyncWriteStream.write`, so the commit above is likely not the culprit.

**Comment by silverwind** [comment] 2016-02-13 14:22
Okay more research:

https://github.com/atom/node/blob/edfbc29d09425f2f387c52d77f6351b6ce101659/lib/fs.js#L1981 is the triggering line, and I can reproduce the error in Atom with `require("child_process").execFileSync("foo")`. So it's just a case of a somewhat misleading error message from node.

So for this bug, it's either that `process.env.SHELL` is set to something weird in Atom (it is `undefined` in a fresh installation, which is fine), or that `/bin/sh` does not exist on the user's system.

**Comment by rickgregory** [comment] 2016-02-13 21:41
Hrm. /bin/sh exists, so that's not it. More info.... 

A fresh atom install which then had an installer of JUST the linter and linter-php plugins reproduces this error. Uninstalling the current versions and dropping back to  linter 1.10.0 and linter-php 1.1.4  works fine. Now let's do the combinations: 

linter 1.10.0 and linter-php 1.1.4 works
linter 1.10.0 and linter-php 1.1.8 fails with t he above error. 
linter 1.11.3 and linter-php 1.1.4 works
linter 1.11.3 and linter-php 1.1.8 fails. 

Note that I can get the same failure with the SCSS linter, etc. So it seems that it's not the linter base plugin that has the issue but some component shared by the language specific linters.

**Comment by Arcanemagus** [comment] 2016-02-13 23:46
@rickgregory Most of the `linter-____` plugins utilize the `atom-linter` module, which in turn uses `consistent-path`, which uses this project to generate some data (that it then does some further messing with).

**Comment by rickgregory** [comment] 2016-02-14 00:48
Got it. I can, if you all want, test more of the linter- plugins. Right now, that seems to be where the issue lies rather than an update to the main linter base plugin.

**Comment by steelbrain** [comment] 2016-02-14 00:49
@rickgregory Yeah, the base linter doesn't do any linting by itself, FYI `linter` is an apm package, `atom-linter` is an npm helper module.

**Comment by silverwind** [comment] 2016-02-14 03:54
@rickgregory I'd still be interested in the value of `process.env.SHELL` while you're getting that error. You can get it with the dev tools, like so:

![screen shot 2016-02-14 at 4 52 39 am](https://cloud.githubusercontent.com/assets/115237/13031735/cee34bda-d2d6-11e5-83d3-d12f37188335.png)

**Comment by rickgregory** [comment] 2016-02-14 06:01
Here ya go: 

"/usr/local/bin/zsh"

**Comment by silverwind** [comment] 2016-02-14 07:40
Does the binary it exist at that location? Any idea where this variable is being set?

**Comment by rickgregory** [comment] 2016-02-14 20:12
Yep.

**Comment by silverwind** [comment] 2016-02-15 10:24
Well, the only explanation I have is that something is wrong with that binary. Do these work?

``` js
require('child_process').execFileSync('/usr/local/bin/zsh', ['--version'], {encoding: 'utf8'})
```

``` js
require('child_process').execFileSync('/usr/local/bin/zsh', ['-ic', 'env'], {encoding: 'utf8'})
```

``` js
require('child_process').execFileSync('/usr/local/bin/zsh', ['-ic', 'echo $PATH'], {encoding: 'utf8'})
```

**Comment by rickgregory** [comment] 2016-02-15 18:34
None of those work. All throw this error: 

Cannot read property 'length' of null(…)SyncWriteStream.write @ fs.js:1981
execFileSync @ child_process.js:471
(anonymous function) @ VM477:2
InjectedScript._evaluateOn @ VM453:904
InjectedScript._evaluateAndWrap @ VM453:837
InjectedScript.evaluate @ VM453:693

**Comment by silverwind** [comment] 2016-02-15 19:36
I wonder what's up with `/usr/local/bin/zsh`. Post the output of these from your terminal:

```
file /usr/local/bin/zsh
```

```
ls -la /usr/local/bin/zsh
```

```
/usr/local/bin/zsh --version
```

**Comment by rickgregory** [comment] 2016-02-15 21:54
AHA... 

/usr/local/bin/zsh: symbolic link in a loop
/usr/local/bin/zsh: Too many levels of symbolic links
lrwxr-xr-x  1 rickg  admin  3 Jul 21  2015 /usr/local/bin/zsh -> zsh

Odd that this would happen now, but... that looks suspicious

**Comment by Arcanemagus** [comment] 2016-02-15 21:57
Wow, how did that manage to get put in place lol.

**Comment by rickgregory** [comment] 2016-02-15 22:00
Yeah... This plus the fact that it's a holiday gives me the  reason I've
been looking for to do a clean install (this Mac has run betas of El
Capitan in the past) so....off to do that

**Comment by silverwind** [comment] 2016-02-15 22:02
I wonder what tool installed that symlink, certainly not brew I think. :smiling_imp:

Does `/bin/zsh` exist and work, by the way? We might be able to detect this issue through `stat`/`lstat` and fallback to it.

**Comment by rickgregory** [comment] 2016-02-15 22:05
Yep,  /bin/zsh exists.

/bin/zsh: Mach-O 64-bit executable x86_64

Actually, I wonder if I should just symlink to that. And yes, I think the
other was a brew thing. Grr....

**Comment by silverwind** [comment] 2016-02-15 22:07
Ah, good. I don't think it was brew, rather something else. My zsh symlink is `/usr/local/bin/zsh => ../Cellar/zsh/5.2/bin/zsh` by the way.

**Comment by rickgregory** [comment] 2016-02-15 22:10
OK. Oddly, I just renamed /usr/local/bin/zsh and created a new symbolic
link to that location from /bin/zsh and still get the above... VERY weird

**Comment by steelbrain** [comment] 2016-02-15 22:11
@rickgregory Can you change your symlink to point to the absolute path `/bin/zsh`?

**Comment by rickgregory** [comment] 2016-02-16 02:26
Oddly, I got the same issue as above. Then I screwed up with the old rm command. I have a clone of the drive before doing this, but I also did a clean install and... the issue doesn't occur. Want more info or shall we write this off as some weird edge case?

**Comment by Arcanemagus** [comment] 2016-02-16 05:49
I'm perfectly fine with writing this off as a bizarre edge case myself, @steelbrain? @silverwind?

**Comment by steelbrain** [comment] 2016-02-16 05:51
This is definitely an edge case, pretty much any program that relies on shell won't be able to function in such a system. Therefore I don't think this is a bug in shell-path

**Comment by rickgregory** [comment] 2016-02-16 07:40
Yeah, the odd thing is that it hasn't seemed to affect other things on the
system and still only affects the latest versions of linter-[N] plugins
(see above that earlier versions of the plugins were OK).

Anyway, I'm fine not pursuing this if you all are OK with it.

**Comment by silverwind** [comment] 2016-02-16 09:56
Okay, I'll close this in favor of https://github.com/sindresorhus/default-shell/issues/2 where we might investigate a more reliable method of getting a user's shell.

**Closed as completed by silverwind** 2016-02-16 09:56 UTC
